# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arnold
email: bertrand.keller@gmail.com
description: Arnold est un artiste de chanson française. Sur cette page vous trouverez les nouvelles relatives à sa musique. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chezarnold.fr"
twitter_username: bertrandkeller
github_username: bertrandkeller
environment: production
repository: bertrandkeller/chezarnold.git

theme: overkyll-jekyll-theme
permalink: pretty

social:
  name: Arnold
  links:
    - https://fr-fr.facebook.com/Arnold-318034885406/

image:
  path: /assets/images/background-arnold.jpg
  height: 100
  width: 100

facebook:
  publisher: 318034885406

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "actualité/:year/:month/:day/"
      image: /assets/images/background-arnold.jpg
  - scope:
      path: "_albums"
    values:
      layout: "albums"
  - scope:
      path: "_chansons"
    values:
      layout: ""

jekyll_tidy:
  ignore_env: development
  compress_html: true

algolia:
  application_id: "DGB0MVTOD1"
  index_name: "chezarnold"
  nodes_to_index: "p,blockquote,li"
  extensions_to_index: "md"
  files_to_exclude:
    - _posts/*.html

# Build settings
markdown: kramdown

exclude:
  - Gemfile.lock
  - node_modules
  - .jekyll-cache

include:
  - actualité
  - _redirects
  #- _headers

collections:
  albums:
    output: true
  chansons:
    output: true

cloudinary:
  cloud_name: dou0m7u5s
  verbose: true
  origin_url: https://chezarnold.fr/
  presets:
    default:
      min_width: 320
      max_width: 1200
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width:40em) 40em, 90vw"

plugins:
  - jekyll-tidy
  - jekyll-commonmark
  - jekyll-feed
